import type { Meal, MealType, Mood } from "../types/index.js";

export interface DishTemplate {
  meal_name: string;
  cuisine: string;
  cooking_time_mins: number;
  difficulty: string;
  meal_type: MealType;
  ingredients: { name: string; qty: number; unit: string }[];
  nutritional_info: { calories: number; protein_g: number; carbs_g: number; fat_g: number; fiber_g: number };
  appliances_needed: string[];
  instructions: string[];
  tags: Mood[];
  dietary: { vegetarian: boolean; onions: boolean; garlic: boolean; dairy: boolean; gluten: boolean; eggs: boolean };
  cost_per_serve: number;
}

export const DISHES: DishTemplate[] = [
  {
    meal_name: "Rava Upma",
    cuisine: "South Indian",
    cooking_time_mins: 15,
    difficulty: "Easy",
    meal_type: "breakfast",
    ingredients: [
      { name: "Semolina (rava)", qty: 200, unit: "g" },
      { name: "Oil", qty: 30, unit: "ml" },
      { name: "Mustard seeds", qty: 5, unit: "g" },
      { name: "Curry leaves", qty: 10, unit: "g" },
      { name: "Onion", qty: 80, unit: "g" },
    ],
    nutritional_info: { calories: 320, protein_g: 8, carbs_g: 45, fat_g: 10, fiber_g: 2 },
    appliances_needed: ["stove"],
    instructions: [
      "Roast semolina in dry pan for 1 minute",
      "Add oil, mustard seeds, curry leaves",
      "Fry until seeds crackle",
      "Add water and salt",
      "Stir until cooked (2 mins)",
    ],
    tags: ["spicy_indian", "budget_minimal"],
    dietary: { vegetarian: true, onions: true, garlic: false, dairy: false, gluten: true, eggs: false },
    cost_per_serve: 15,
  },
  {
    meal_name: "Masala Dosa",
    cuisine: "South Indian",
    cooking_time_mins: 30,
    difficulty: "Medium",
    meal_type: "breakfast",
    ingredients: [
      { name: "Rice", qty: 150, unit: "g" },
      { name: "Urad dal", qty: 50, unit: "g" },
      { name: "Potato", qty: 200, unit: "g" },
      { name: "Onion", qty: 80, unit: "g" },
      { name: "Turmeric", qty: 2, unit: "g" },
    ],
    nutritional_info: { calories: 420, protein_g: 12, carbs_g: 62, fat_g: 12, fiber_g: 4 },
    appliances_needed: ["stove", "mixer"],
    instructions: [
      "Grind rice and urad dal into batter",
      "Cook potato masala with turmeric and onions",
      "Spread batter on hot tawa",
      "Fill with masala and fold",
    ],
    tags: ["spicy_indian"],
    dietary: { vegetarian: true, onions: true, garlic: false, dairy: false, gluten: true, eggs: false },
    cost_per_serve: 25,
  },
  {
    meal_name: "Egg Bhurji on Toast",
    cuisine: "Indian",
    cooking_time_mins: 12,
    difficulty: "Easy",
    meal_type: "breakfast",
    ingredients: [
      { name: "Eggs", qty: 4, unit: "pc" },
      { name: "Bread", qty: 4, unit: "pc" },
      { name: "Onion", qty: 60, unit: "g" },
      { name: "Tomato", qty: 60, unit: "g" },
      { name: "Oil", qty: 20, unit: "ml" },
    ],
    nutritional_info: { calories: 380, protein_g: 22, carbs_g: 30, fat_g: 18, fiber_g: 2 },
    appliances_needed: ["stove", "microwave"],
    instructions: [
      "Saute onions and tomatoes in oil",
      "Scramble eggs and mix in",
      "Toast bread",
      "Serve bhurji on toast",
    ],
    tags: ["protein_packed", "quick_easy"],
    dietary: { vegetarian: false, onions: true, garlic: false, dairy: false, gluten: false, eggs: true },
    cost_per_serve: 30,
  },
  {
    meal_name: "Paneer Paratha",
    cuisine: "North Indian",
    cooking_time_mins: 25,
    difficulty: "Medium",
    meal_type: "breakfast",
    ingredients: [
      { name: "Wheat flour (atta)", qty: 200, unit: "g" },
      { name: "Paneer", qty: 150, unit: "g" },
      { name: "Onion", qty: 60, unit: "g" },
      { name: "Ghee", qty: 20, unit: "ml" },
      { name: "Green chilli", qty: 10, unit: "g" },
    ],
    nutritional_info: { calories: 480, protein_g: 18, carbs_g: 55, fat_g: 20, fiber_g: 5 },
    appliances_needed: ["stove"],
    instructions: [
      "Knead atta dough",
      "Mix crumbled paneer with spices",
      "Stuff dough with paneer filling",
      "Roll and roast on tawa with ghee",
    ],
    tags: ["protein_packed"],
    dietary: { vegetarian: true, onions: true, garlic: false, dairy: true, gluten: false, eggs: false },
    cost_per_serve: 35,
  },
  {
    meal_name: "Vegetable Poha",
    cuisine: "Indian",
    cooking_time_mins: 12,
    difficulty: "Easy",
    meal_type: "breakfast",
    ingredients: [
      { name: "Poha (flattened rice)", qty: 180, unit: "g" },
      { name: "Peanuts", qty: 30, unit: "g" },
      { name: "Potato", qty: 100, unit: "g" },
      { name: "Onion", qty: 60, unit: "g" },
      { name: "Oil", qty: 20, unit: "ml" },
    ],
    nutritional_info: { calories: 300, protein_g: 7, carbs_g: 48, fat_g: 9, fiber_g: 3 },
    appliances_needed: ["stove"],
    instructions: [
      "Rinse poha and set aside",
      "Saute peanuts, potato, onion",
      "Add poha and steam briefly",
      "Garnish with lemon and coriander",
    ],
    tags: ["quick_easy", "budget_minimal"],
    dietary: { vegetarian: true, onions: true, garlic: false, dairy: false, gluten: true, eggs: false },
    cost_per_serve: 12,
  },
  {
    meal_name: "Moong Dal Chilla",
    cuisine: "North Indian",
    cooking_time_mins: 20,
    difficulty: "Easy",
    meal_type: "breakfast",
    ingredients: [
      { name: "Moong dal", qty: 150, unit: "g" },
      { name: "Onion", qty: 50, unit: "g" },
      { name: "Ginger", qty: 10, unit: "g" },
      { name: "Oil", qty: 15, unit: "ml" },
    ],
    nutritional_info: { calories: 340, protein_g: 20, carbs_g: 42, fat_g: 9, fiber_g: 6 },
    appliances_needed: ["stove", "mixer"],
    instructions: [
      "Soak and grind moong dal into batter",
      "Mix in chopped onion and ginger",
      "Spread on hot tawa like dosa",
      "Cook both sides until crisp",
    ],
    tags: ["protein_packed", "low_calorie", "quick_easy"],
    dietary: { vegetarian: true, onions: true, garlic: false, dairy: false, gluten: true, eggs: false },
    cost_per_serve: 15,
  },
  {
    meal_name: "Dal Fry",
    cuisine: "North Indian",
    cooking_time_mins: 20,
    difficulty: "Easy",
    meal_type: "lunch",
    ingredients: [
      { name: "Toor dal", qty: 200, unit: "g" },
      { name: "Tomato", qty: 80, unit: "g" },
      { name: "Onion", qty: 60, unit: "g" },
      { name: "Ghee", qty: 15, unit: "ml" },
      { name: "Turmeric", qty: 3, unit: "g" },
    ],
    nutritional_info: { calories: 350, protein_g: 14, carbs_g: 48, fat_g: 10, fiber_g: 8 },
    appliances_needed: ["cooker", "stove"],
    instructions: [
      "Pressure cook dal with turmeric",
      "Temper ghee with onion, tomato",
      "Mix tadka into dal",
      "Simmer for 2 minutes",
    ],
    tags: ["spicy_indian", "budget_minimal"],
    dietary: { vegetarian: true, onions: true, garlic: false, dairy: true, gluten: true, eggs: false },
    cost_per_serve: 20,
  },
  {
    meal_name: "Jeera Rice",
    cuisine: "North Indian",
    cooking_time_mins: 15,
    difficulty: "Easy",
    meal_type: "lunch",
    ingredients: [
      { name: "Basmati rice", qty: 250, unit: "g" },
      { name: "Cumin seeds", qty: 5, unit: "g" },
      { name: "Ghee", qty: 15, unit: "ml" },
    ],
    nutritional_info: { calories: 360, protein_g: 7, carbs_g: 65, fat_g: 7, fiber_g: 1 },
    appliances_needed: ["cooker", "stove"],
    instructions: [
      "Wash and soak rice for 15 mins",
      "Temper cumin seeds in ghee",
      "Cook rice with water until done",
      "Fluff and serve",
    ],
    tags: ["spicy_indian", "budget_minimal"],
    dietary: { vegetarian: true, onions: false, garlic: false, dairy: true, gluten: true, eggs: false },
    cost_per_serve: 15,
  },
  {
    meal_name: "Paneer Butter Masala",
    cuisine: "North Indian",
    cooking_time_mins: 30,
    difficulty: "Medium",
    meal_type: "lunch",
    ingredients: [
      { name: "Paneer", qty: 200, unit: "g" },
      { name: "Tomato", qty: 200, unit: "g" },
      { name: "Cream", qty: 50, unit: "ml" },
      { name: "Butter", qty: 20, unit: "g" },
      { name: "Onion", qty: 60, unit: "g" },
    ],
    nutritional_info: { calories: 520, protein_g: 24, carbs_g: 28, fat_g: 36, fiber_g: 4 },
    appliances_needed: ["stove", "mixer"],
    instructions: [
      "Blend tomato and onion into puree",
      "Saute puree in butter",
      "Add cream and simmer",
      "Add paneer cubes, cook 5 mins",
    ],
    tags: ["spicy_indian"],
    dietary: { vegetarian: true, onions: true, garlic: false, dairy: true, gluten: true, eggs: false },
    cost_per_serve: 55,
  },
  {
    meal_name: "Chicken Curry",
    cuisine: "North Indian",
    cooking_time_mins: 35,
    difficulty: "Medium",
    meal_type: "lunch",
    ingredients: [
      { name: "Chicken", qty: 300, unit: "g" },
      { name: "Onion", qty: 100, unit: "g" },
      { name: "Tomato", qty: 150, unit: "g" },
      { name: "Oil", qty: 25, unit: "ml" },
      { name: "Garam masala", qty: 5, unit: "g" },
    ],
    nutritional_info: { calories: 480, protein_g: 38, carbs_g: 20, fat_g: 28, fiber_g: 3 },
    appliances_needed: ["cooker", "stove"],
    instructions: [
      "Saute onions till golden",
      "Add tomatoes and spices",
      "Add chicken, cook covered",
      "Garnish and serve",
    ],
    tags: ["protein_packed"],
    dietary: { vegetarian: false, onions: true, garlic: false, dairy: false, gluten: true, eggs: false },
    cost_per_serve: 60,
  },
  {
    meal_name: "Mixed Vegetable Curry",
    cuisine: "North Indian",
    cooking_time_mins: 25,
    difficulty: "Easy",
    meal_type: "lunch",
    ingredients: [
      { name: "Potato", qty: 150, unit: "g" },
      { name: "Cauliflower", qty: 150, unit: "g" },
      { name: "Carrot", qty: 100, unit: "g" },
      { name: "Peas", qty: 80, unit: "g" },
      { name: "Oil", qty: 20, unit: "ml" },
    ],
    nutritional_info: { calories: 320, protein_g: 9, carbs_g: 40, fat_g: 12, fiber_g: 8 },
    appliances_needed: ["cooker", "stove"],
    instructions: [
      "Chop all vegetables",
      "Saute with spices in oil",
      "Add water and cook covered",
      "Simmer until tender",
    ],
    tags: ["low_calorie", "quick_easy", "budget_minimal"],
    dietary: { vegetarian: true, onions: false, garlic: false, dairy: false, gluten: true, eggs: false },
    cost_per_serve: 25,
  },
  {
    meal_name: "Rajma Chawal",
    cuisine: "North Indian",
    cooking_time_mins: 30,
    difficulty: "Medium",
    meal_type: "lunch",
    ingredients: [
      { name: "Rajma (kidney beans)", qty: 200, unit: "g" },
      { name: "Rice", qty: 200, unit: "g" },
      { name: "Onion", qty: 80, unit: "g" },
      { name: "Tomato", qty: 100, unit: "g" },
      { name: "Ghee", qty: 15, unit: "ml" },
    ],
    nutritional_info: { calories: 480, protein_g: 20, carbs_g: 75, fat_g: 10, fiber_g: 12 },
    appliances_needed: ["cooker", "stove"],
    instructions: [
      "Pressure cook rajma till soft",
      "Saute onion, tomato masala",
      "Add rajma and simmer",
      "Serve with steamed rice",
    ],
    tags: ["spicy_indian", "budget_minimal"],
    dietary: { vegetarian: true, onions: true, garlic: false, dairy: true, gluten: true, eggs: false },
    cost_per_serve: 30,
  },
  {
    meal_name: "Grilled Chicken Salad",
    cuisine: "Continental",
    cooking_time_mins: 20,
    difficulty: "Easy",
    meal_type: "lunch",
    ingredients: [
      { name: "Chicken breast", qty: 250, unit: "g" },
      { name: "Lettuce", qty: 100, unit: "g" },
      { name: "Cucumber", qty: 100, unit: "g" },
      { name: "Tomato", qty: 100, unit: "g" },
      { name: "Olive oil", qty: 15, unit: "ml" },
    ],
    nutritional_info: { calories: 350, protein_g: 40, carbs_g: 12, fat_g: 16, fiber_g: 4 },
    appliances_needed: ["stove", "microwave"],
    instructions: [
      "Season and grill chicken breast",
      "Chop salad vegetables",
      "Toss with olive oil",
      "Slice chicken over salad",
    ],
    tags: ["protein_packed", "low_calorie", "quick_easy"],
    dietary: { vegetarian: false, onions: false, garlic: false, dairy: false, gluten: true, eggs: false },
    cost_per_serve: 70,
  },
  {
    meal_name: "Palak Paneer",
    cuisine: "North Indian",
    cooking_time_mins: 30,
    difficulty: "Medium",
    meal_type: "dinner",
    ingredients: [
      { name: "Spinach", qty: 300, unit: "g" },
      { name: "Paneer", qty: 200, unit: "g" },
      { name: "Onion", qty: 60, unit: "g" },
      { name: "Tomato", qty: 80, unit: "g" },
      { name: "Cream", qty: 30, unit: "ml" },
    ],
    nutritional_info: { calories: 430, protein_g: 22, carbs_g: 18, fat_g: 30, fiber_g: 6 },
    appliances_needed: ["stove", "mixer"],
    instructions: [
      "Blanch and blend spinach",
      "Saute onion and tomato masala",
      "Add spinach puree and cream",
      "Add paneer cubes, simmer",
    ],
    tags: ["spicy_indian"],
    dietary: { vegetarian: true, onions: true, garlic: false, dairy: true, gluten: true, eggs: false },
    cost_per_serve: 45,
  },
  {
    meal_name: "Curd Rice",
    cuisine: "South Indian",
    cooking_time_mins: 10,
    difficulty: "Easy",
    meal_type: "dinner",
    ingredients: [
      { name: "Rice", qty: 200, unit: "g" },
      { name: "Curd (yogurt)", qty: 250, unit: "g" },
      { name: "Mustard seeds", qty: 3, unit: "g" },
      { name: "Oil", qty: 10, unit: "ml" },
    ],
    nutritional_info: { calories: 380, protein_g: 10, carbs_g: 58, fat_g: 10, fiber_g: 1 },
    appliances_needed: ["cooker", "stove"],
    instructions: [
      "Cook rice and cool it",
      "Mix curd into rice",
      "Temper mustard seeds in oil",
      "Pour tadka and serve",
    ],
    tags: ["quick_easy", "budget_minimal", "low_calorie"],
    dietary: { vegetarian: true, onions: false, garlic: false, dairy: true, gluten: true, eggs: false },
    cost_per_serve: 18,
  },
  {
    meal_name: "Vegetable Khichdi",
    cuisine: "Indian",
    cooking_time_mins: 25,
    difficulty: "Easy",
    meal_type: "dinner",
    ingredients: [
      { name: "Rice", qty: 150, unit: "g" },
      { name: "Moong dal", qty: 100, unit: "g" },
      { name: "Carrot", qty: 80, unit: "g" },
      { name: "Peas", qty: 60, unit: "g" },
      { name: "Ghee", qty: 15, unit: "ml" },
    ],
    nutritional_info: { calories: 400, protein_g: 15, carbs_g: 60, fat_g: 10, fiber_g: 7 },
    appliances_needed: ["cooker", "stove"],
    instructions: [
      "Wash rice and moong dal",
      "Add vegetables and ghee",
      "Pressure cook for 3 whistles",
      "Serve hot with curd",
    ],
    tags: ["quick_easy", "low_calorie", "budget_minimal"],
    dietary: { vegetarian: true, onions: false, garlic: false, dairy: true, gluten: true, eggs: false },
    cost_per_serve: 20,
  },
  {
    meal_name: "Masala Omelette",
    cuisine: "Indian",
    cooking_time_mins: 10,
    difficulty: "Easy",
    meal_type: "dinner",
    ingredients: [
      { name: "Eggs", qty: 4, unit: "pc" },
      { name: "Onion", qty: 50, unit: "g" },
      { name: "Tomato", qty: 60, unit: "g" },
      { name: "Green chilli", qty: 10, unit: "g" },
      { name: "Oil", qty: 15, unit: "ml" },
    ],
    nutritional_info: { calories: 320, protein_g: 22, carbs_g: 8, fat_g: 24, fiber_g: 2 },
    appliances_needed: ["stove"],
    instructions: [
      "Whisk eggs with chopped veggies",
      "Heat oil in pan",
      "Pour and cook both sides",
      "Serve with bread",
    ],
    tags: ["protein_packed", "quick_easy"],
    dietary: { vegetarian: false, onions: true, garlic: false, dairy: false, gluten: true, eggs: true },
    cost_per_serve: 25,
  },
  {
    meal_name: "Chana Masala",
    cuisine: "North Indian",
    cooking_time_mins: 25,
    difficulty: "Easy",
    meal_type: "dinner",
    ingredients: [
      { name: "Chickpeas (kabuli chana)", qty: 250, unit: "g" },
      { name: "Onion", qty: 80, unit: "g" },
      { name: "Tomato", qty: 100, unit: "g" },
      { name: "Garam masala", qty: 4, unit: "g" },
      { name: "Oil", qty: 20, unit: "ml" },
    ],
    nutritional_info: { calories: 390, protein_g: 16, carbs_g: 55, fat_g: 12, fiber_g: 12 },
    appliances_needed: ["cooker", "stove"],
    instructions: [
      "Pressure cook chickpeas",
      "Saute onion tomato masala",
      "Add chickpeas and simmer",
      "Garnish with coriander",
    ],
    tags: ["spicy_indian", "budget_minimal"],
    dietary: { vegetarian: true, onions: true, garlic: false, dairy: false, gluten: true, eggs: false },
    cost_per_serve: 25,
  },
  {
    meal_name: "Vegetable Stir-fry with Rice",
    cuisine: "Indo-Chinese",
    cooking_time_mins: 20,
    difficulty: "Easy",
    meal_type: "dinner",
    ingredients: [
      { name: "Rice", qty: 200, unit: "g" },
      { name: "Broccoli", qty: 150, unit: "g" },
      { name: "Capsicum", qty: 100, unit: "g" },
      { name: "Soy sauce", qty: 15, unit: "ml" },
      { name: "Oil", qty: 20, unit: "ml" },
    ],
    nutritional_info: { calories: 420, protein_g: 12, carbs_g: 62, fat_g: 12, fiber_g: 6 },
    appliances_needed: ["stove", "microwave"],
    instructions: [
      "Cook rice and cool",
      "Stir-fry vegetables in oil",
      "Add soy sauce",
      "Mix with rice and toss",
    ],
    tags: ["quick_easy", "low_calorie"],
    dietary: { vegetarian: true, onions: false, garlic: false, dairy: false, gluten: false, eggs: false },
    cost_per_serve: 30,
  },
];

export const SEASONAL: Record<string, { cheap: string[]; expensive: string[]; note: string }> = {
  jan: { cheap: ["Onion", "Tomato", "Leafy greens"], expensive: ["Mango", "Berries"], note: "Winter - onion-based, earthy greens" },
  feb: { cheap: ["Onion", "Tomato", "Leafy greens"], expensive: ["Mango", "Berries"], note: "Winter - onion-based, earthy greens" },
  mar: { cheap: ["Mango", "Lychee", "Berries"], expensive: ["Leafy greens"], note: "Summer - mango-based, light meals" },
  apr: { cheap: ["Mango", "Lychee", "Berries"], expensive: ["Leafy greens"], note: "Summer - mango-based, light meals" },
  may: { cheap: ["Mango", "Lychee", "Berries"], expensive: ["Leafy greens"], note: "Summer - mango-based, light meals" },
  jun: { cheap: ["Leafy greens", "Root vegetables"], expensive: ["Tomato"], note: "Monsoon - spinach, root veggies" },
  jul: { cheap: ["Leafy greens", "Root vegetables"], expensive: ["Tomato"], note: "Monsoon - spinach, root veggies" },
  aug: { cheap: ["Leafy greens", "Root vegetables"], expensive: ["Tomato"], note: "Monsoon - spinach, root veggies" },
  sep: { cheap: ["Onion", "Tomato"], expensive: ["Mango"], note: "Autumn - North Indian, onion-heavy" },
  oct: { cheap: ["Onion", "Tomato"], expensive: ["Mango"], note: "Autumn - North Indian, onion-heavy" },
  nov: { cheap: ["Onion", "Tomato"], expensive: ["Mango"], note: "Autumn - North Indian, onion-heavy" },
  dec: { cheap: ["Winter vegetables", "Leafy greens"], expensive: ["Fruits"], note: "Year-end - traditional winter dishes" },
};
